Traceback (most recent call last):
  File "feature_select_AA.py", line 39, in <module>
    df_binary_labeled = df_labeled.drop(columns=['sample_id', 'age', 'white', 'black', 'hispanic', 'asian', 'male', 'female'], axis=1)
  File "/apps/software/standard/core/anaconda/2020.11-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 4163, in drop
    return super().drop(
  File "/apps/software/standard/core/anaconda/2020.11-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 3887, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/apps/software/standard/core/anaconda/2020.11-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 3921, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/apps/software/standard/core/anaconda/2020.11-py3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5282, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['age' 'asian'] not found in axis"
